# Generated by Django 4.2 on 2023-04-08 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('english', '0002_wordimage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordimage',
            name='url',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='wordimage',
            name='user',
        ),
        migrations.AddField(
            model_name='wordimage',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
