# Generated by Django 4.2 on 2023-04-08 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_alter_wordimage_url_remove_wordimage_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordimage',
            old_name='user',
            new_name='users',
        ),
    ]
