# Generated by Django 4.1.7 on 2023-04-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0004_rename_user_wordimage_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninglist',
            name='learned',
            field=models.BooleanField(default=False),
        ),
    ]
