# Generated by Django 4.1.7 on 2023-04-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0005_learninglist_learned'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninglist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2023-04-09 00:00:00'),
            preserve_default=False,
        ),
    ]
