# Generated by Django 4.1.7 on 2023-04-09 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0006_learninglist_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listreview',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='english.learninglist'),
        ),
    ]
