# Generated by Django 4.2 on 2023-04-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0007_alter_listreview_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='last_review',
            field=models.DateTimeField(auto_now_add=True, default='2023-4-09'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learninglist',
            name='words',
            field=models.ManyToManyField(blank=True, related_name='words', to='english.word'),
        ),
    ]
