# Generated by Django 4.2 on 2023-04-14 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0010_alter_wordimage_users_alter_wordimage_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='english.level'),
        ),
    ]
