# Generated by Django 4.2 on 2023-04-15 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0011_alter_word_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordimage',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.word'),
        ),
    ]
