# Generated by Django 4.2 on 2023-04-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0012_alter_wordimage_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninglist',
            name='words',
            field=models.ManyToManyField(blank=True, to='english.word'),
        ),
    ]
