# Generated by Django 4.2 on 2023-04-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0013_alter_learninglist_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='last_review',
            field=models.DateTimeField(default='2023.16.04'),
        ),
    ]
