# Generated by Django 4.2 on 2023-04-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0016_wordlastreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlastreview',
            name='datetime',
            field=models.DateTimeField(default='2023-04-16'),
        ),
    ]
