# Generated by Django 4.2 on 2023-04-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0017_wordlastreview_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlastreview',
            name='datetime',
            field=models.DateTimeField(default='2023.04.16'),
        ),
    ]
